site_name: Social Wallet
site_url: https://commonfare-net.github.io/social-wallet-api
repo_url: https://github.com/commonfare-net/social-wallet-api
site_author: Jaromil
site_description: The Social Wallet API  is made to facilitate the integration of blockchain functions into existing front-end applications
copyright: Copyright (C) 2019 by the <a href="https://dyne.org">Dyne.org foundation</a>. The source code is licensed <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3</a>.

extra:
  links:
    releases: https://github.com/Commonfare-net/social-wallet-api/releases
    docker: https://hub.docker.com/r/dyne/social-wallet-api
    forum: https://lists.dyne.org
  drift_handle: s64nd7w43g53
  h2020: "687922"
  nav:
    subtitle: Open source complementary currency toolkit
    logo: null # /img/redroom-trans.png
    og_image_large: /img/logo-trans.png


plugins: []

extra_css:
  - //fonts.googleapis.com/css?family=Montserrat&display=swap
  - css/custom.css

markdown_extensions:
  - admonition
  - codehilite

theme:
  name: null
  custom_dir: 'mkdocs-dyne-theme/'
